package JAN_27;

public class FEB_3 {
    public static void main(String[] args) {
        try{
            //your statement goes here
            int data = 12/0;

            //Exception occurs in try block and handled in catch block
        }
        catch(Exception e){
            //you can catch and handle your exception here
            System.out.println(e);
        }
    }
}
